CREATE TABLE IF NOT EXISTS users(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	middle_name VARCHAR(100),
	birthdate DATE CHECK (birthdate > '1900-01-01'),
	phone VARCHAR(20) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(20) NOT NULL CHECK (role IN ('STUDENT', 'MANAGER'))
);

CREATE TABLE IF NOT EXISTS student_profiles(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	institute VARCHAR(200),
	group_name VARCHAR(50),
	course INT CHECK (course BETWEEN 1 AND 6)
);

CREATE TABLE IF NOT EXISTS shifts(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	title VARCHAR(200) NOT NULL,
	description TEXT,
	start_datetime TIMESTAMPTZ NOT NULL CHECK (start_datetime > '2000-01-01'),
	end_datetime TIMESTAMPTZ NOT NULL CHECK (end_datetime > '2000-01-01' AND end_datetime > start_datetime),
	required_people INT NOT NULL CHECK (required_people > 0),
	created_by INT REFERENCES users(id) ON DELETE SET NULL,
	status VARCHAR(20) DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'IN_WORK', 'COMPLETED', 'CANCELED')),
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP CHECK (created_at > '2000-01-01')
);

CREATE TABLE IF NOT EXISTS tickets(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	title VARCHAR(200) NOT NULL,
	description TEXT,
	status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'IN_WORK', 'COMPLETED', 'CANCELED')),
	shift_id INT NOT NULL REFERENCES shifts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_tickets(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	user_id INT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
	ticket_id INT REFERENCES tickets(id) ON DELETE RESTRICT,
	status VARCHAR(20) DEFAULT 'IN_WORK' CHECK (status IN ('IN_WORK', 'DONE', 'CANCELED')),
	taken_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP CHECK (taken_at > '2000-01-01'),
	completed_at TIMESTAMPTZ CHECK (completed_at > taken_at OR completed_at IS NULL),

	CONSTRAINT uq_user_ticket UNIQUE (user_id, ticket_id)
);

CREATE TABLE IF NOT EXISTS shift_bookings(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	user_id INT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
	shift_id INT NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
	booked_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP CHECK (booked_at > '2000-01-01'),
	started_at TIMESTAMPTZ CHECK (started_at > booked_at),
	finished_at TIMESTAMPTZ CHECK (finished_at > started_at),
	status VARCHAR(20) DEFAULT 'BOOKED' CHECK (
		status IN ('BOOKED', 'IN_PROGRESS', 'PENDING_APPROVAL', 'COMPLETED', 'CANCELLED', 'EXCHANGED')
	),
	cancellation_reason TEXT
);

CREATE TABLE IF NOT EXISTS exchange_requests(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	initiator_id INT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
	shift_booking_id INT NOT NULL REFERENCES shift_bookings(id) ON DELETE CASCADE,
	reason TEXT NOT NULL,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP CHECK (created_at > '2000-01-01'),
	status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);